# Generated by Django 4.2.7 on 2023-11-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReciclajeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseIncentivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('valorPorKilo', models.CharField(max_length=50)),
                ('promocion', models.CharField(max_length=15)),
            ],
        ),
    ]
