# Generated by Django 4.2.7 on 2024-09-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReciclajeApp', '0003_clasecuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Telefono', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClaseMuni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=50)),
            ],
        ),
    ]
