# Generated by Django 4.2.7 on 2024-09-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReciclajeApp', '0004_clasecontacto_clasemuni'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClaseRecicla',
            new_name='ClasePunto',
        ),
    ]
