# Generated by Django 4.2.7 on 2024-09-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReciclajeApp', '0005_rename_claserecicla_clasepunto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClaseIncentivos',
            new_name='ClaseIncentivo',
        ),
    ]
