# Generated by Django 4.2.7 on 2024-09-27 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReciclajeApp', '0006_rename_claseincentivos_claseincentivo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClaseCuenta',
            new_name='ClaseCuentaB',
        ),
    ]
