# Generated by Django 4.2.7 on 2024-09-27 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReciclajeApp', '0007_rename_clasecuenta_clasecuentab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaseMuni',
        ),
    ]
