# Generated by Django 4.2.7 on 2024-09-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReciclajeApp', '0008_delete_clasemuni'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseMuni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=50)),
            ],
        ),
    ]
