# Generated by Django 4.2.7 on 2024-09-28 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReciclajeApp', '0009_clasemuni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaseContacto',
        ),
    ]
