# Generated by Django 5.1.2 on 2024-10-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReciclajeApp', '0011_clasecontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseLogin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
            ],
        ),
    ]
