# Generated by Django 5.1.2 on 2024-10-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReciclajeApp', '0012_claselogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='claselogin',
            name='recontrasena',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
