# Generated by Django 5.1.2 on 2024-10-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReciclajeApp', '0014_alter_claselogin_recontrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claselogin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
