# Generated by Django 5.1.2 on 2024-12-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReciclajeApp', '0016_rename_contrasena_claselogin_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claselogin',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='claselogin',
            name='recontrasena',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='claselogin',
            name='username',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
