# Generated by Django 5.1.2 on 2024-12-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReciclajeApp', '0017_alter_claselogin_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasecuentab',
            name='Correo',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='claseincentivo',
            name='promocion',
            field=models.CharField(max_length=128),
        ),
    ]
